from django.urls import path
from . import views

urlpatterns = [
    path('<str:first_name>/<str:last_name>/<int:age>/<str:date_of_birth>/<str:gender>/create_user/',
         views.UserDetailsViewSet.as_view({'post': 'create'}), name="create_user"),
    path('<int:user_id>/<str:education_details>/<int:score>/<str:institute_name>/create_education/',
         views.EducationDetailsViewSet.as_view({'post': 'create'}), name="create_education"),
    path('<int:user_id>/<str:company_name>/<str:start_year>/<str:end_year>/<int:package>/create_company/',
         views.CompanyDetailsViewSet.as_view({'post': 'create'}), name="create_company"),
    path('<int:user_id>/<str:achievement>/<str:year>/create_achievement/',
         views.AchievementDetailsViewSet.as_view({'post': 'create'}), name="create_achievement"),
    path('get_users/',
         views.GetUserDetailsViewSet.as_view({'get': 'list'}), name="get_users"),
    path('get_education_details/',
         views.GetEducationDetailsViewSet.as_view({'get': 'list'}), name="get_education_details"),
    path('get_company_details/',
         views.GetCompanyDetailsViewSet.as_view({'get': 'list'}), name="get_company_details"),
    path('get_achievements/',
         views.GetAchievementDetailsViewSet.as_view({'get': 'list'}), name="get_achievements"),
    path('<int:user_id>/get_user/',
         views.GetUserViewSet.as_view({'get': 'list'}), name="get_user"),
    path('<int:user_id>/get_user_education/',
         views.GetUserEducationDetailsViewSet.as_view({'get': 'list'}), name="get_user_education"),
    path('<int:user_id>/get_user_company/',
         views.GetUserCompanyDetailsViewSet.as_view({'get': 'list'}), name="get_user_company"),
    path('<int:user_id>/get_user_achievement/',
         views.GetUserAchievementDetailsViewSet.as_view({'get': 'list'}), name="get_user_achievement"),
    path('<int:user_id>/<str:first_name>/<str:last_name>/<int:age>/<str:date_of_birth>/<str:gender>/update_user/',
         views.UpdateUserDetailsViewSet.as_view({'put': 'update'}), name="update_user"),
    path('<int:user_id>/<str:education_details>/<int:score>/<str:institute_name>/update_education/',
         views.UpdateEducationDetailsViewSet.as_view({'put': 'update'}), name="update_user_education"),
    path('<int:user_id>/<str:company_name>/<str:start_year>/<str:end_year>/<int:package>/update_company/',
         views.UpdateCompanyDetailsViewSet.as_view({'put': 'update'}), name="update_user_company"),
    path('<int:user_id>/<str:achievement>/<str:year>/update_user_achievement/',
         views.AchievementDetailsViewSet.as_view({'put': 'update'}), name="update_user_achievement"),
    path('<int:user_id>/delete_user/',
         views.DeleteUserDetailsViewSet.as_view({'delete': 'destroy'}), name="delete_user"),
    path('<int:user_id>/delete_user_education/',
         views.DeleteEducationDetailsViewSet.as_view({'delete': 'destroy'}), name="delete_user_education"),
    path('<int:user_id>/delete_user_company/',
         views.DeleteCompanyDetailsViewSet.as_view({'delete': 'destroy'}), name="delete_user_company"),
    path('<int:user_id>/delete_user_achievement/',
         views.DeleteAchievementDetailsViewSet.as_view({'delete': 'destroy'}), name="delete_user_achievement")
]