# Generated by Django 4.0.5 on 2022-07-08 17:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0002_class_student'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='class_id',
            new_name='class_stu_id',
        ),
    ]
