# Generated by Django 4.0.5 on 2022-07-09 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0004_group_person_membership_group_members'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ox',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('horn_length', models.IntegerField()),
            ],
            options={
                'verbose_name_plural': 'oxen',
                'ordering': ['horn_length'],
            },
        ),
    ]
