# Generated by Django 4.0.5 on 2022-07-16 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facebook', '0002_snippet'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='id_number',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
