# Generated by Django 4.0.5 on 2022-07-17 17:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('facebook', '0003_user_id_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about_comment', models.CharField(max_length=500)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='facebook.post')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='facebook.user')),
            ],
        ),
        migrations.DeleteModel(
            name='Snippet',
        ),
    ]
