# Generated by Django 4.0.5 on 2022-07-26 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='end_year',
            field=models.DateField(default=None),
        ),
        migrations.AlterField(
            model_name='education',
            name='education_details',
            field=models.CharField(choices=[('10th', '10th'), ('Intermediate', 'Intermediate'), ('Graduation', 'Graduation')], max_length=600),
        ),
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=200),
        ),
    ]
